# Site settings

highlighter: true

title: Structured Prediction

description: > 
 Structured Prediction (CS 6355), Spring 2021

baseurl: "/teaching/structured-prediction/spring2021" 
lectures: "/teaching/lectures"

url: "https://svivek.com" 


# Build settings
markdown: kramdown

year: Spring 2021
coursenumber: "CS 6355"

classtime: "Tue & Thu, 9:10AM -- 10:30PM"

canvas: https://utah.instructure.com/courses/669125

videoicon: "[**video**]"
